application: app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /(bower_components)/(.*).(js|css|png|jpg|html)
  static_files: static/\1/\2.\3
  upload: static/.*.(js|css|png|jpg|html)

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /_ah/spi/.*
  script: main.application
